# Generated by Django 4.1.7 on 2023-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_note_description_alter_reference_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='my_datetime_field',
            field=models.DateTimeField(default='2023-03-16 19:21:33'),
        ),
    ]
