# Generated by Django 4.1.7 on 2023-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_note_my_datetime_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='my_datetime_field',
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-16 19:21:43'),
        ),
    ]
