# Generated by Django 4.1.7 on 2023-03-18 10:19

import Notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_alter_note_time_alter_reference_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-18 10:19:20'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(),
        ),
    ]
