# Generated by Django 4.1.7 on 2023-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0012_alter_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-18 12:08:26'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(),
        ),
    ]
