# Generated by Django 4.1.7 on 2023-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_alter_note_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-18 13:03:13'),
        ),
    ]
