# Generated by Django 4.1.7 on 2023-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_alter_note_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='cover_image',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-19 07:58:52'),
        ),
    ]
