# Generated by Django 4.1.7 on 2023-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0018_rename_cover_image_note_cover_alter_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-03-19 07:59:06'),
        ),
    ]
