# Generated by Django 4.1.7 on 2023-06-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0032_alter_note_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default='2023-06-25 19:42:57'),
        ),
    ]
