# Generated by Django 4.1.7 on 2023-06-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0030_alter_note_time'),
        ('Notes', '0033_rename_public_note_is_public_alter_note_time'),
    ]

    operations = [
    ]
